<a href="https://colab.research.google.com/github/rama96/pytorch_tutorials/blob/master/Introduction_to_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to PytTorch

## Tensors

In [1]:
import torch
import numpy as np

### Conversion from numpy

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

np_array = np.array([[1, 2],[3, 4]])
x_np = torch.tensor(np_array)

### Majorly used torch functions for tensor manipulations 

1. torch.rand 
2. torch.ones 
3. torch.zeros 
4. torch.cat


In [8]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(f"Concatenated tensors")
print(tensor)
print(t1)
print(t1.shape)

Random Tensor: 
 tensor([[0.9751, 0.6613, 0.4911],
        [0.4382, 0.1616, 0.3994]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
Concatenated tensors
tensor([[0.4638, 0.3129, 0.5920, 0.0384],
        [0.7367, 0.3447, 0.1271, 0.6630],
        [0.5547, 0.8782, 0.7304, 0.6689]])
tensor([[0.4638, 0.3129, 0.5920, 0.0384, 0.4638, 0.3129, 0.5920, 0.0384, 0.4638,
         0.3129, 0.5920, 0.0384],
        [0.7367, 0.3447, 0.1271, 0.6630, 0.7367, 0.3447, 0.1271, 0.6630, 0.7367,
         0.3447, 0.1271, 0.6630],
        [0.5547, 0.8782, 0.7304, 0.6689, 0.5547, 0.8782, 0.7304, 0.6689, 0.5547,
         0.8782, 0.7304, 0.6689]])
torch.Size([3, 12])


By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability). 

In [4]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
  


In [9]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### Arithmetic Operations

In [13]:
# Matrix multiplication , y1 and y2 would have the same value

tensor = torch.rand(3,4)

print(tensor)
 
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

# Checks element wise equality 
print(torch.eq(y1, y2))

# Checks overall equality
print(torch.equal(y1, y2))




tensor([[0.7697, 0.2927, 0.7619, 0.8249],
        [0.7652, 0.6868, 0.2431, 0.7702],
        [0.0704, 0.2619, 0.4642, 0.1377]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
True


In [14]:
# This computes the element-wise product. z1, z2 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

# Checks element wise equality 
print(torch.eq(z1, z2))

# Checks overall equality
print(torch.equal(z1, z2))


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
True


## Datasets and Dataloaders
